name: flutter_ready_layout
description: "Execute code once immediately after a widget’s first layout/frame is complete."
version: 1.0.0
homepage: https://github.com/UsmanTechOfficial/flutter-ready-layout
maintainer: M_Usman <usmantech.me@gmail.com>

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
